services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/code/app
    ports:
      - "80:80"
    env_file:
      - .env
 
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./sql/migration.sql:/docker-entrypoint-initdb.d/migration.sql
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - .env